STOCHASTIC GRADIENT DESCENT

In [50]:
import numpy as np

Generate random data,
X represents input features, Y represents target values

In [51]:
np.random.seed(42)
X = 2 + np.random.rand(100,1)
Y = 4 + 3 * X + np.random.randn(100,1) 
print(X)
print(Y)

[[2.37454012]
 [2.95071431]
 [2.73199394]
 [2.59865848]
 [2.15601864]
 [2.15599452]
 [2.05808361]
 [2.86617615]
 [2.60111501]
 [2.70807258]
 [2.02058449]
 [2.96990985]
 [2.83244264]
 [2.21233911]
 [2.18182497]
 [2.18340451]
 [2.30424224]
 [2.52475643]
 [2.43194502]
 [2.29122914]
 [2.61185289]
 [2.13949386]
 [2.29214465]
 [2.36636184]
 [2.45606998]
 [2.78517596]
 [2.19967378]
 [2.51423444]
 [2.59241457]
 [2.04645041]
 [2.60754485]
 [2.17052412]
 [2.06505159]
 [2.94888554]
 [2.96563203]
 [2.80839735]
 [2.30461377]
 [2.09767211]
 [2.68423303]
 [2.44015249]
 [2.12203823]
 [2.49517691]
 [2.03438852]
 [2.9093204 ]
 [2.25877998]
 [2.66252228]
 [2.31171108]
 [2.52006802]
 [2.54671028]
 [2.18485446]
 [2.96958463]
 [2.77513282]
 [2.93949894]
 [2.89482735]
 [2.59789998]
 [2.92187424]
 [2.0884925 ]
 [2.19598286]
 [2.04522729]
 [2.32533033]
 [2.38867729]
 [2.27134903]
 [2.82873751]
 [2.35675333]
 [2.28093451]
 [2.54269608]
 [2.14092422]
 [2.80219698]
 [2.07455064]
 [2.98688694]
 [2.77224477]
 [2.19

Add a bias term to X

In [52]:
X_b = np.c_[np.ones((100,1)),X]
print(X_b)

[[1.         2.37454012]
 [1.         2.95071431]
 [1.         2.73199394]
 [1.         2.59865848]
 [1.         2.15601864]
 [1.         2.15599452]
 [1.         2.05808361]
 [1.         2.86617615]
 [1.         2.60111501]
 [1.         2.70807258]
 [1.         2.02058449]
 [1.         2.96990985]
 [1.         2.83244264]
 [1.         2.21233911]
 [1.         2.18182497]
 [1.         2.18340451]
 [1.         2.30424224]
 [1.         2.52475643]
 [1.         2.43194502]
 [1.         2.29122914]
 [1.         2.61185289]
 [1.         2.13949386]
 [1.         2.29214465]
 [1.         2.36636184]
 [1.         2.45606998]
 [1.         2.78517596]
 [1.         2.19967378]
 [1.         2.51423444]
 [1.         2.59241457]
 [1.         2.04645041]
 [1.         2.60754485]
 [1.         2.17052412]
 [1.         2.06505159]
 [1.         2.94888554]
 [1.         2.96563203]
 [1.         2.80839735]
 [1.         2.30461377]
 [1.         2.09767211]
 [1.         2.68423303]
 [1.         2.44015249]


Initialize model parameters

In [53]:
theta = np.random.randn(2,1)
theta

array([[0.01300189],
       [1.45353408]])

Hperparameters

In [54]:
learning_rate = 0.1
n_iterations = 1000

Gradient Descent

In [55]:
for iteration in range(n_iterations):
    gradients = 2 * X_b.T.dot(Y - X_b.dot(theta))
    theta -= learning_rate * gradients
print(theta)    

[[-inf]
 [-inf]]


Optimal Parameters

In [56]:
intercept, slope = theta
print("Intercept:",intercept[0])
print("Slope:",slope[0])

Intercept: -inf
Slope: -inf


LINEAR REGRESSION

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
X = np.random.rand(100,1) * 10
y = 2 * X +3 + np.random.randn(100,1)
class LinearRegression:
    def __init__(self):
        self.weights = None
        self.bias = None
    
    def fit(self,X,y,learning_rate=0.01, epoch = 20):
        num_samples, num_features = X.shape
        self.weights = np.zeros((num_features,1))
        self.bias = 0

        for _ in range(epoch):
             y_pred = np.dot(X,self.weights) + self.bias
             dw = (1 / num_samples) * np.dot(X.T,(y_pred - y)) 
             db = (1 / num_samples) * np.sum(y_pred - y) 
             self.weights -= learning_rate * dw
             self.bias -= learning_rate * db

    def predict (self,X):
        return np.dot(X,self.weights) +self.bias

model =  LinearRegression()
model.fit(X,y,learning_rate=0.01,epoch=20)
X_test = np.array([[1],[5],[10]])
y_pred = model.predict(X_test)

plt.scatter(X,y,label='Training Data')
plt.plot(X_test,y_pred,color='red',label='Linear Regression')
plt.xlabel('X')
plt.ylabel('y')
plt.title('Linear Regression using NumPy')
plt.legend()
plt.show()

